# Generated by Django 3.0.6 on 2020-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200530_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmessage',
            options={'verbose_name': 'Contact Form Message', 'verbose_name_plural': 'Contact Form Message'},
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Closed', 'Kapalı')], default='New', max_length=10),
        ),
    ]
