# Generated by Django 3.0.6 on 2020-06-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='city',
        ),
    ]
