# Generated by Django 3.0.6 on 2020-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faq_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='siranumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
